TakaMaka/TakaMaka/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url('admin/', admin.site.urls),
    url('animalSpirits/', include('animalSpirits.urls')),
]

TakaMaka/animalSpirits/urls.py
from django.conf.urls import url
from . import views

app_name = 'animalSpirits'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'about/', views.about, name='about'),
    url(r'aboutUs/', views.aboutUs, name='aboutUs'),
    url(r'rules/', views.rules, name='rules'),
    url(r'timer/', views.timer, name='timer'),
    url(r'evaluation/', views.evaluate, name='evaluation'),
]

TakaMaka/animalSpirits/models.py
from django.db import models

# Create your models here.

TakaMaka/animalSpirits/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'animalSpirits/index.html')


def about(request):
    return render(request, 'animalSpirits/about.html')


def aboutUs(request):
    return render(request, 'animalSpirits/aboutUs.html')


def rules(request):
    return render(request, 'animalSpirits/rules.html')


def timer(request):
    return render(request, 'animalSpirits/timer.html')


def evaluate(request):
    return render(request, 'animalSpirits/evaluate.html')

TakaMaka/animalSpirits/templates/animalSpirits/about.html
{% extends 'animalSpirits/base.html' %}
{% block title %}Game info{% endblock %}


{% block body %}
GAME INFO
{% endblock %}

TakaMaka/animalSpirits/templates/animalSpirits/aboutUs.html
{% extends 'animalSpirits/base.html' %}
{% block title %}About Us{% endblock %}

{% block body %}
ABOUT US
{% endblock %}

TakaMaka/animalSpirits/templates/animalSpirits/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'animalSpirits/MainPage.css' %}">
    <link rel="stylesheet" href="{% static 'animalSpirits/myChart.css' %}">
    <link rel="stylesheet" href="{% static 'animalSpirits/cardsEvaluation.css' %}">
</head>
<body>
    <header>
        <h1>Animal Spirits</h1>
    </header>

    <a href="{% url 'animalSpirits:evaluation' %}">Evaluate</a>

    {% block body %}
    {% endblock %}
</body>
</html>

TakaMaka/animalSpirits/templates/animalSpirits/evaluate.html
{% extends 'animalSpirits/base.html' %}
{% block title %}Evaluation{% endblock %}

{% block body %}
<div class="container">
        <section></section>
</div>

{% load static %}
<script src="{% static 'animalSpirits/js/cardsEvaluation.js' %}" type="module"></script>
{% endblock %}

TakaMaka/animalSpirits/templates/animalSpirits/index.html
{% extends 'animalSpirits/base.html' %}
{% block title %}Animal Spirits{% endblock %}

{% block body %}
<main class="Game">
    <a class="Game__StartButton" href="{% url 'animalSpirits:timer' %}">Play</a>
</main>
<nav class="Navigation">
    <ul class="Navigation__list">
        <li class="Navigation__item"><a class="Navigation__link" href="{% url 'animalSpirits:about' %}">Про гру</a></li>
        <li class="Navigation__item"><a class="Navigation__link" href="{% url 'animalSpirits:rules' %}">Правила</a></li>
        <li class="Navigation__item"><a class="Navigation__link" href="{% url 'animalSpirits:aboutUs' %}">Про нас</a></li>
    </ul>
</nav>
{% endblock %}

TakaMaka/animalSpirits/templates/animalSpirits/rules.html
{% extends 'animalSpirits/base.html' %}
{% block title %}Rules{% endblock %}


{% block body %}
RULES
{% endblock %}

TakaMaka/animalSpirits/templates/animalSpirits/timer.html
{% extends 'animalSpirits/base.html' %}
{% block title %}Timer{% endblock %}

{% block body %}
    <ul class="Game__PriceList">
        <li class="Game__PriceItem"><img class="Game__Card" /><div class="Game__StockPrice">1</div></li>
        <li class="Game__PriceItem"><img class="Game__Card" /><div class="Game__StockPrice">2</div></li>
        <li class="Game__PriceItem"><img class="Game__Card" /><div class="Game__StockPrice">3</div></li>
        <li class="Game__PriceItem"><img class="Game__Card" /><div class="Game__StockPrice">4</div></li>
    </ul>
    <div class="Timer">
        <span class="Timer__time">
            06:00
        </span>
        <button class="Timer__start">
            Start
        </button>
    </div>
    {% load static %}
    <script src="{% static 'animalSpirits/js/index.js' %}" type="module"></script>
{% endblock %}